apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/24sunrin015/gj2025-repository.git
    targetRevision: gitops-green
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: skills
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

