apiVersion: v1
kind: Service
metadata:
  name: green-service
  namespace: skills
  labels:
    app: green
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: green
