apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        serviceAccount:
          name: external-secrets-sa
          namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::156041424727:role/gj2025-external-secrets-role
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: skills
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: db-secret
  data:
    - secretKey: DB_USER
      remoteRef:
        key: gj2025-eks-cluster-catalog-secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: gj2025-eks-cluster-catalog-secret
        property: DB_PASSWORD
    - secretKey: DB_URL
      remoteRef:
        key: gj2025-eks-cluster-catalog-secret
        property: DB_URL
